CREATE TABLE IF NOT EXISTS stats
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app_name VARCHAR(255) NOT NULL,
    user_ip  VARCHAR(15)  NOT NULL,
    created  TIMESTAMP    NOT NULL,
    uri      VARCHAR(255) NOT NULL
);

CREATE INDEX IF NOT EXISTS name_index ON stats (app_name);

CREATE INDEX IF NOT EXISTS ip_index ON stats (user_ip);

CREATE INDEX IF NOT EXISTS created_index ON stats (created);

CREATE INDEX IF NOT EXISTS uri_index ON stats (uri);